### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ghost** [ProgramistaZpolski/programistazpolski#1]
czemu robisz multikonta na twitterze

**Comment by ghost** [comment]
to bardzo dobre pytanie

**Comment by piotrbadelek** [comment]
1. The sieciuchy account - for memes
2. The pzplui account - to post updates on the project
any more questions?

**Comment by ghost** [comment]
to jest akurat repo do twojego profilu
a nazwa twojego profilu, wyraźnie mówi że jesteś Z POLSKI, więc nie mów po angielsku, dziękuje

**Comment by ghost** [comment]
> 
> 
> to jest akurat repo do twojego profilu
> a nazwa twojego profilu, wyraźnie mówi że jesteś Z POLSKI, więc nie mów po angielsku, dziękuje

this

**Comment by piotrbadelek** [comment]
No

polish is the worst language and I refuse to speak it

**Comment by ghost** [comment]
ale rozmawiasz z ludźmi Z POLSKI, więc mów PO POLSKU
napisałbym coś, lecz zaraz wykorzystasz to jako następny materiał do trollowania

**Comment by piotrbadelek** [comment]
> > to jest akurat repo do twojego profilu
> > a nazwa twojego profilu, wyraźnie mówi że jesteś Z POLSKI, więc nie mów po angielsku, dziękuje
> 
> this

![Screenshot from 2021-03-08 21-31-32](https://user-images.githubusercontent.com/37271169/110378272-aee8cd00-8055-11eb-90e3-94f1d4590cb3.png)

this

**Comment by ghost** [comment]
> > > to jest akurat repo do twojego profilu
> > > a nazwa twojego profilu, wyraźnie mówi że jesteś Z POLSKI, więc nie mów po angielsku, dziękuje
> > 
> > 
> > this
> 
> ![Screenshot from 2021-03-08 21-31-32](https://user-images.githubusercontent.com/37271169/110378272-aee8cd00-8055-11eb-90e3-94f1d4590cb3.png)
> 
> this

disstream

**Comment by ghost** [comment]
bardzo śmieszne, dobra zamykam, bo z takim trollem jak ty nie warto rozmawiać

**Comment by ghost** [comment]
2137

**Comment by piotrbadelek** [comment]
You want to be banned?

Also stop spamming my email

**Comment by ghost** [comment]
*banned*

to nie typowy serwerek HC w minecrafcie, tylko github, tutaj co najwyzej mozesz kogos zablokować, co ci nic nie da
btw. nie ma za co
hhhhhhhhhhhhh

**Comment by piotrbadelek** [comment]
Why are nonstop editing this

**Comment by ghost** [comment]
zebys mial spam na emailu

**Comment by piotrbadelek** [comment]
it does not spam my email

edits do not give me emails

**Comment by piotrbadelek** [comment]
also you blocked me so I get exactly 0 emails from you

**Comment by ghost** [comment]
fivstfi6uskfvtyusfvtsau 7f78nshjkfsyu kbhsdov svlisbdilvbsivstoyvbtsduyvstyl vds

**Comment by ghost** [comment]
> 
> 
> You want to be banned?
> 
> Also stop spamming my email

🏳️‍🌈

**Comment by ghost** [comment]
czemu oznaczyłeś flagę LGBT jako spam? homofobie

**Comment by ghost** [comment]
SPAM XDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by ghost** [comment]
dlaczego dyskrymiunjesz galaretki, twardogórzan, radomsko, oraz patelnie?

**Comment by piotrbadelek** [comment]
what

**Comment by piotrbadelek** [comment]
Also, could you please stop raiding my repos?

**Comment by ghost** [comment]
no dlaczego dyskrymiunjesz galaretki, twardogórzan, radomsko, oraz patelnie? wszyscy wymienieni to członkowie społeczności LGBT

**Comment by ghost** [comment]
weź to reopenuj xD @TheVision6212
