### ISSUE TITLE
tak jak nizej

### ISSUE THREAD

**Issue by ghost** [ProgramistaZpolski/programistazpolski#2]
tak jak nizej

zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij zdechnij

**Comment by piotrbadelek** [comment]
why

**Comment by ghost** [comment]
DO KOGO Z WAS?
*MUZYKA*

**Comment by ghost** [comment]
TELEFONY W MOJEJ GLOWIE

**Comment by ghost** [comment]
BEZ PRZERWY

**Comment by ghost** [comment]
NIKT NIE DZWONI NIKT NIE DZWONIIIIIII

**Comment by ghost** [comment]
TO TYLKO JAAA (TYLKO JA) (JA)

**Comment by ghost** [comment]
telefony w mojej glowie (nanananana)

**Comment by ghost** [comment]
telefony w mojej glowie (nanananana)

**Comment by ghost** [comment]
telefony w mojej glowie (nanananana)

**Comment by ghost** [comment]
TO TYLKO JA

**Comment by ghost** [comment]
TAM GDZIE DZWONIĘ NIE POZNAJĄ
MEGO GŁOSU, GŁOSU, GŁO-SU, GŁO.. SU!

**Comment by ghost** [comment]
ąąąąąąąąąąąąąąąąąąąą
KTO WYDZWONI KTO WYKRĘCI
WKOŃCU NUMER MÓÓÓÓÓÓÓÓÓÓÓÓÓÓJ

**Comment by ghost** [comment]
KTO ZADZWONI KTO... ZADZWONI TUTAJ- DO MNIE...

**Comment by ghost** [comment]
TELEFONY, TELE- FONY WCIĄŻ

**Comment by ghost** [comment]
TELEFONY W MOJEJ GŁOWIE WCIĄŻ

**Comment by ghost** [comment]
TELEFONY W MOJEJ GŁOWIE WCIĄŻ

**Comment by ghost** [comment]
TO TYLKO JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by ghost** [comment]
TELEFONY W MOJEJ GŁOWIE

**Comment by ghost** [comment]
BEZ PRZERWY
TRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR

**Comment by ghost** [comment]
NIKT NIE DZWONI
NIKT NIE DZWONI

**Comment by ghost** [comment]
TO TYLKO JA TYLKO JA JA

**Comment by ghost** [comment]
telefony w mojej głowie
telefony w mojej głowie
telefony w mojej głowie
to tylko ja!

**Comment by ghost** [comment]
na na na na na na na

**Comment by ghost** [comment]
nanananananananana

**Comment by ghost** [comment]
na na na na na na na

**Comment by ghost** [comment]
nanananananananana

**Comment by ghost** [comment]
na na na na na na na

**Comment by ghost** [comment]
nanananananananana

**Comment by ghost** [comment]
na na na na na na na...

**Comment by ghost** [comment]
nanananananananana..

**Comment by ghost** [comment]
na na na na na na na

**Comment by ghost** [comment]
nanananananananana

**Comment by ghost** [comment]
na na na na na na na

**Comment by ghost** [comment]
nanananananananana

**Comment by ghost** [comment]
na na na na na na na

**Comment by ghost** [comment]
nanananananananana

**Comment by ghost** [comment]
na na na na na na naaaaaaaaaaaa...
