### ISSUE TITLE
TELEFONY TELEFONY

### ISSUE THREAD

**Issue by ghost** [ProgramistaZpolski/programistazpolski#3]
THIS COMMENT WAS REMOVED

**Comment by ghost** [comment]
I JAKI NUMER MAM WYKRĘCIĆ?

**Comment by ghost** [comment]
DO KOGO Z WAAAAAAAAAAAS?

**Comment by ghost** [comment]
TELEFONY TELEFOONYYY
*NANANANANA*

**Comment by piotrbadelek** [comment]
Please stop propagating evil.
